
version: "3"

services:  

  nginx:
    image: nginx
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=80
    ports:
      - 9090:80
    volumes:
      - ./static:/usr/share/nginx/html:ro
  
  zk:
    build: ./zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_VERSION: 3.4.11
    volumes:
      - ./.data/zookeeper:/opt/zookeeper-3.4.11/data
  
  data01:
    build: ./ignite
    ports:
      - 18081:8080
    depends_on:
      - nginx
      - zk
    env_file:
      - .env
    volumes:
      - ./.data/ignite/data01:/opt/ignite/apache-ignite/work

  data02:
    build: ./ignite
    ports:
      - 18082:8080
    depends_on:
      - nginx
      - zk
    env_file:
      - .env
    volumes:
      - ./.data/ignite/data02:/opt/ignite/apache-ignite/work
