
version: "3"

services:  

  nginx:
    image: nginx
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=80
    ports:
      - 9090:80
    volumes:
      - ./static:/usr/share/nginx/html:ro
  
  zk:
    build: ./zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_VERSION: 3.4.11
    volumes:
      - ./.data/zookeeper:/opt/zookeeper-3.4.11/data
  
  data01:
    image: apacheignite/ignite:2.7.0
    ports:
      - 8080:8080
    depends_on:
      - nginx
      - zk
    environment:
      CONFIG_URI: http://nginx/zk-cache.xml
      OPTION_LIBS: "ignite-rest-http ignite-zookeeper"
